name: hitbitz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_localization: ^3.0.3
  extended_image: ^8.1.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_blurhash: ^0.8.2
  flutter_file_dialog: ^3.0.2
  flutter_local_notifications: ^16.2.0
  flutter_reorderable_list: ^1.3.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.0.1
  font_awesome_flutter: ^10.6.0
  gap: ^3.0.1
  get_it: ^7.6.4
  go_router: ^13.0.0
  http: ^1.1.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.5
  injectable: ^2.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  restart_app: ^1.2.1
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.2
  vibration: ^1.8.4

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/translations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 800
