// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1wRgsaaFWqypYSc3WbFWi4DL5IWbRRk',
    appId: '1:919955493032:web:6f141deeafaf6f7060f29d',
    messagingSenderId: '919955493032',
    projectId: 'hitbitz',
    authDomain: 'hitbitz.firebaseapp.com',
    storageBucket: 'hitbitz.appspot.com',
    measurementId: 'G-Z6K8WP2TWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCOIO_ZZfOiaBhRTElB9fX9VGdT0GppXI',
    appId: '1:919955493032:android:f5b74c09ebbbb5a660f29d',
    messagingSenderId: '919955493032',
    projectId: 'hitbitz',
    storageBucket: 'hitbitz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG_YjPsA0brOkKoHFJNFj2DDWwIDvxIE8',
    appId: '1:919955493032:ios:82b6d0bbf3f00f3b60f29d',
    messagingSenderId: '919955493032',
    projectId: 'hitbitz',
    storageBucket: 'hitbitz.appspot.com',
    iosBundleId: 'com.example.hitbitz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA1wRgsaaFWqypYSc3WbFWi4DL5IWbRRk',
    appId: '1:919955493032:web:8fdb2c6df73e06d460f29d',
    messagingSenderId: '919955493032',
    projectId: 'hitbitz',
    authDomain: 'hitbitz.firebaseapp.com',
    storageBucket: 'hitbitz.appspot.com',
    measurementId: 'G-CCTXFM2MDC',
  );
}
