import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  background: Color(0xfffcfcfc),
  onBackground: Color(0xff191C1D),
  primary: Color(0xff6949FF),
  onPrimary: Color(0xffFFFFFF),
  primaryContainer: Color(0xff3FA03D),
  onPrimaryContainer: Color(0xffFFFFFF),
  secondary: Color(0xffE8C07D),
  onSecondary: Color(0xffFFFFFF), //Color(0xff0D120E),
  secondaryContainer: Color(0xfffcebcc),
  onSecondaryContainer: Color(0xffC79F5C),
  tertiary: Color(0xffef9818),
  onTertiary: Color(0xffFFFFFF),
  tertiaryContainer: Color(0xfffbf4ea),
  onTertiaryContainer: Color(0xffC79F5C),
  error: Color(0xffBA1A1A),
  onError: Color(0xffFFFFFF),
  errorContainer: Color(0xffFFDAD5),
  onErrorContainer: Color(0xff410002),
  surface: Color(0xffFFFFFF),
  onSurface: Color(0xff303030),
  inverseSurface: Color(0xff2E3132),
  onInverseSurface: Color(0xff7F909F),
  surfaceTint: Color(0xffeef4f2),
  // surfaceVariant: Color(0xffDBE4E6),
  onSurfaceVariant: Color(0xff706F80),
  outline: Color(0xffe3e5e5),
  outlineVariant: Color(0xffE4E9EA),
  // inversePrimary: Color(0xffFFB7AD),
  shadow: Color(0xff191C1D),
  scrim: Color(0xff191C1D),
);
