import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  background: Color(0xffffffff),
  onBackground: Color(0xff4b4b4b),
  primary: Color(0xfff9ad2b),
  // primary: Color(0xff6A5AE0),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xfffef5e5),
  onPrimaryContainer: Color(0xfff9ad2b),
  secondary: Color(0xfff9ad2b),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xfffcd28c),
  onSecondaryContainer: Color(0xff4b4b4b),
  tertiary: Color(0xff12d18e),
  onTertiary: Color(0xffffffff),
  // tertiaryContainer: Color(0xfffbf4ea),
  // onTertiaryContainer: Color(0xffC79F5C),
  error: Color(0xfff75555),
  onError: Color(0xffffffff),
  // errorContainer: Color(0xffFFDAD5),
  // onErrorContainer: Color(0xff410002),
  surface: Color(0xffffffff),
  onSurface: Color(0xff212021),
  // inverseSurface: Color(0xff2E3132),
  // onInverseSurface: Color(0xff7F909F),
  // surfaceTint: Color(0xffe9e9e9),
  surfaceVariant: Color(0xffe9e9e9),
  onSurfaceVariant: Color(0xff787878),
  outline: Color(0xffbcbcbc),
  outlineVariant: Color(0xff787878),
  // inversePrimary: Color(0xffFFB7AD),
  shadow: Color(0xff191C1D),
  scrim: Color(0xff191C1D),
);
